# This is a basic workflow to help you get started with ActionsfgfgIDK

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branchhello
  pull_request:


  # Allows you to run this workflow manually from the Actions tab idkffff
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallelgurll
jobs:
  # This workflow contains a single job called "build"dfsfsfd
  build:
    # The type of runner that the job will run onfdfd
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it helffflo how
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Change file
        run: |
          git checkout master
          git config user.email "demo@everr.com"
          git merge --no-ff origin/${{github.head_ref}} -m "demo"
          npm install -g semantic-release
          npx semantic-release --no-ci --branches master
